# agents/code_export.py — Code Export Agent
# Generates a runnable Jupyter notebook from pipeline results

import json


def generate_notebook(df_raw, cleaned_df, insights, audit_log,
                       dataset_name="dataset.csv"):
    numeric_cols = df_raw.select_dtypes(include=["number"]).columns.tolist()
    n_rows, n_cols = df_raw.shape

    def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src.strip()}
    def md(src):   return {"cell_type":"markdown","metadata":{},"source":src.strip()}

    cells = [
        md(f"# DataForge — Data Science Notebook\n**Dataset:** `{dataset_name}` | {n_rows:,} rows × {n_cols} columns\n\nGenerated by DataForge AI Agent. Run each cell to reproduce the analysis."),
        md("## 1. Setup"),
        code("import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport plotly.express as px\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.preprocessing import StandardScaler, LabelEncoder\nfrom sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\nfrom sklearn.linear_model import LogisticRegression, LinearRegression\nfrom sklearn.metrics import accuracy_score, r2_score\nimport warnings; warnings.filterwarnings('ignore')\nprint('Libraries loaded!')"),
        md("## 2. Load Data"),
        code(f"df = pd.read_csv('{dataset_name}')  # change path as needed\nprint(f'Loaded: {{df.shape[0]:,}} rows x {{df.shape[1]}} columns')\ndf.head()"),
        md(f"## 3. Data Cleaning\n\nDataForge applied these steps:\n" + "\n".join(f"- {e}" for e in audit_log[:8])),
        code("# Standardise column names\ndf.columns = df.columns.str.strip().str.replace(' ','_').str.lower()\n\n# Remove duplicates\nbefore = len(df)\ndf = df.drop_duplicates()\nprint(f'Removed {before - len(df)} duplicate rows')\n\n# Fill missing values\nfor col in df.select_dtypes(include=[np.number]).columns:\n    if df[col].isnull().sum() > 0:\n        df[col] = df[col].fillna(df[col].median())\n\nfor col in df.select_dtypes(include=['object']).columns:\n    if df[col].isnull().sum() > 0:\n        df[col] = df[col].fillna(df[col].mode()[0])\n\nprint(f'Missing values remaining: {df.isnull().sum().sum()}')\nprint(f'Clean dataset: {df.shape[0]:,} rows x {df.shape[1]} columns')"),
        code("# Detect outliers (IQR method — flag, do not remove)\nfor col in df.select_dtypes(include=[np.number]).columns:\n    Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)\n    IQR = Q3 - Q1\n    n = ((df[col] < Q1-1.5*IQR) | (df[col] > Q3+1.5*IQR)).sum()\n    if n > 0: print(f'{col}: {n:,} outliers flagged')"),
        md("## 4. Statistical Analysis"),
        code("# Descriptive statistics\ndf.describe().round(3)"),
        code("# Correlation matrix\ncorr = df.select_dtypes(include=[np.number]).corr().round(3)\nprint('Strong correlations (|r| > 0.5):')\nfor i in range(len(corr.columns)):\n    for j in range(i+1, len(corr.columns)):\n        r = corr.iloc[i,j]\n        if abs(r) > 0.5:\n            print(f'  {corr.columns[i]} <-> {corr.columns[j]}: r={r:.3f}')"),
        code("# Skewness\nskew = df.select_dtypes(include=[np.number]).skew().round(3).sort_values(ascending=False)\nfor col, s in skew.items():\n    flag = ' HIGH SKEW' if abs(s) > 2 else ''\n    print(f'{col}: {s:.3f}{flag}')"),
        md("## 5. Visualisation"),
        code(f"# Histograms\nnum_cols = df.select_dtypes(include=[np.number]).columns.tolist()[:4]\nfig, axes = plt.subplots(1, len(num_cols), figsize=(len(num_cols)*4, 4))\nfor i, col in enumerate(num_cols):\n    ax = axes[i] if len(num_cols) > 1 else axes\n    ax.hist(df[col].dropna(), bins=30, color='#02C39A', alpha=0.8)\n    ax.set_title(col.replace('_',' ').title())\nplt.suptitle('Distributions', fontweight='bold')\nplt.tight_layout(); plt.show()"),
        code("# Correlation heatmap\nfig, ax = plt.subplots(figsize=(10,8))\nmask = np.triu(np.ones_like(corr, dtype=bool))\nsns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdYlGn', center=0, ax=ax)\nax.set_title('Correlation Heatmap', fontweight='bold')\nplt.tight_layout(); plt.show()"),
        md("## 6. Machine Learning (AutoML)"),
        code("# Set target column\ntarget_col = df.columns[-1]  # change to any column\nX = df.drop(columns=[target_col]).select_dtypes(include=[np.number])\ny = df[target_col]\n\n# Encode if categorical\nif y.dtype == 'object':\n    le = LabelEncoder(); y = le.fit_transform(y); task = 'classification'\nelse:\n    task = 'classification' if y.nunique() <= 10 else 'regression'\n\nprint(f'Target: {target_col} | Task: {task}')"),
        code("# Train and compare models\nscaler = StandardScaler()\nX_sc = scaler.fit_transform(X)\nX_tr, X_te, y_tr, y_te = train_test_split(X_sc, y, test_size=0.2, random_state=42)\n\nif task == 'classification':\n    models = {'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),\n              'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42)}\n    metric, score_fn = 'accuracy', accuracy_score\nelse:\n    models = {'Linear Regression': LinearRegression(),\n              'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42)}\n    metric, score_fn = 'r2', r2_score\n\nbest_score, best_name, best_model = -1, None, None\nfor name, model in models.items():\n    model.fit(X_tr, y_tr)\n    score = score_fn(y_te, model.predict(X_te))\n    print(f'{name}: {score:.4f}')\n    if score > best_score: best_score, best_name, best_model = score, name, model\nprint(f'\\nBest: {best_name} ({best_score:.4f})')"),
        md("## 7. Save Results"),
        code("df.to_csv('cleaned_dataset.csv', index=False)\nprint('Saved cleaned_dataset.csv')\nprint('Analysis complete!')")
    ]

    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {"kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
                     "language_info": {"name":"python","version":"3.12.0"}},
        "cells": cells
    }


def notebook_to_bytes(notebook):
    return json.dumps(notebook, indent=2).encode("utf-8")