# agents/reporter.py
# Agent 4 — GPT-4o-mini Natural Language Report Writer

import json
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()


def generate_report(insights: dict, audit_log: list, client) -> str:
    summary = {
        "dataset_shape": insights.get("shape", {}),
        "columns": insights.get("columns", []),
        "numeric_summary": {
            k: {stat: val for stat, val in v.items()}
            for k, v in insights.get("numeric_summary", {}).items()
        },
        "strong_correlations": insights.get("strong_correlations", []),
        "categorical_summary": {
            col: data.get("top_5", {})
            for col, data in insights.get("categorical_summary", {}).items()
        },
        "skewed_columns": insights.get("skewed_columns", {}),
        "bias_warnings": insights.get("bias_warnings", []),
        "cleaning_log": audit_log[-5:],
    }

    prompt = f"""
You are DataForge, an expert autonomous data analyst AI.
You have just processed a dataset and gathered the following insights:

{json.dumps(summary, indent=2)}

Write a professional, structured data analysis report in Markdown.
Include: Executive Summary, Dataset Overview, Key Statistical Findings,
Correlations, Data Quality Notes, Bias Warnings, and Recommendations.
Do NOT make up data that is not in the provided insights.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are DataForge, a professional AI data analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.4,
        max_tokens=1500
    )
    return response.choices[0].message.content


def generate_report_fallback(insights: dict, audit_log: list) -> str:
    shape = insights.get("shape", {})
    cols = insights.get("columns", [])
    numeric = insights.get("numeric_summary", {})
    correlations = insights.get("strong_correlations", [])
    categorical = insights.get("categorical_summary", {})
    skewed = insights.get("skewed_columns", {})
    bias_warnings = insights.get("bias_warnings", [])

    lines = []
    lines.append("# DataForge Analysis Report\n")
    lines.append("*Generated autonomously by DataForge AI Agent*\n")
    lines.append("---\n")
    lines.append("## 1. Executive Summary\n")
    lines.append(f"The dataset contains **{shape.get('rows', '?')} rows** and "
                 f"**{shape.get('cols', '?')} columns**. "
                 f"A total of **{len(cols)} features** were examined, "
                 f"with **{len(numeric)} numeric** and **{len(categorical)} categorical** columns.\n")
    lines.append("## 2. Dataset Overview\n")
    lines.append(f"- **Total rows:** {shape.get('rows', 'N/A')}")
    lines.append(f"- **Total columns:** {shape.get('cols', 'N/A')}")
    lines.append(f"- **Numeric columns:** {', '.join(numeric.keys()) if numeric else 'None'}")
    lines.append(f"- **Categorical columns:** {', '.join(categorical.keys()) if categorical else 'None'}\n")
    lines.append("## 3. Key Statistical Findings\n")
    if numeric:
        for col, stats in list(numeric.items())[:5]:
            lines.append(f"**{col}**: mean={stats.get('mean')}, std={stats.get('std')}, min={stats.get('min')}, max={stats.get('max')}")
        lines.append("")
    lines.append("## 4. Correlations & Relationships\n")
    if correlations:
        for pair in correlations:
            strength = "positive" if pair["correlation"] > 0 else "negative"
            lines.append(f"- **{pair['col_a']}** and **{pair['col_b']}**: {strength} (r = {pair['correlation']})")
    else:
        lines.append("No strong correlations detected.\n")
    lines.append("## 5. Data Quality Notes\n")
    for entry in audit_log:
        lines.append(f"- {entry}")
    lines.append("")
    lines.append("## 6. Bias & Fairness Warnings\n")
    if bias_warnings:
        for w in bias_warnings:
            lines.append(f"- {w}")
    else:
        lines.append("No significant bias concerns detected.")
    lines.append("")
    lines.append("## 7. Recommendations\n")
    recs = [
        "Validate cleaning steps against domain knowledge before modelling.",
        "Investigate flagged outliers before using data in production.",
    ]
    if skewed:
        recs.append(f"Apply log transformation to skewed columns: {', '.join(skewed.keys())}.")
    recs.append("Run this pipeline regularly to track data changes over time.")
    for i, rec in enumerate(recs, 1):
        lines.append(f"{i}. {rec}")
    lines.append("\n---")
    lines.append("*Report generated by DataForge*")
    return "\n".join(lines)
